### ISSUE TITLE
socket hang up

### ISSUE THREAD

**Issue by capaj** [TimSamshuijzen/iotaproxy#5] opened 2017-09-03 22:44 UTC
I tried sending a transaction, but I never got past this error which is in the callback of `sendTransfer()`:

```
Error: Invalid Response: Error: socket hang up
    at createHangUpError (_http_client.js:345:15)
    at Socket.socketOnEnd (_http_client.js:437:23)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Object.invalidResponse (/home/capaj/git_projects/gratiota/node_modules/iota.lib.js/lib/errors/requestErrors.js:5:12)
    at makeRequest.prepareResult (/home/capaj/git_projects/gratiota/node_modules/iota.lib.js/lib/utils/makeRequest.js:159:24)
    at exports.XMLHttpRequest.request.onreadystatechange (/home/capaj/git_projects/gratiota/node_modules/iota.lib.js/lib/utils/makeRequest.js:61:25)
    at exports.XMLHttpRequest.dispatchEvent (/home/capaj/git_projects/gratiota/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/home/capaj/git_projects/gratiota/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at exports.XMLHttpRequest.handleError (/home/capaj/git_projects/gratiota/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:532:5)
    at ClientRequest.errorHandler (/home/capaj/git_projects/gratiota/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:459:14)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at Socket.socketOnEnd (_http_client.js:437:9)
```

this is weird, because by default node.js socket does not have any timeout.

BTW I am on ubuntu 17.04

**Comment by TimSamshuijzen** [comment] 2017-09-08 22:52
Hi capaj, I haven't tested it on Ubuntu, only on Windows. Does the problem still persist after applying the fix you committed recently?

**Comment by capaj** [comment] 2017-09-09 06:22
Yes it does. That one was only a minor issue because it was assigned on global. It wasn't breaking anything.

**Comment by TimSamshuijzen** [comment] 2017-09-09 13:09
I am hoping others encounter this problem too and help determine what the problem is. Anyone else having this problem?

**Comment by cyclux** [comment] 2017-09-09 17:54
I also encountered this error but not always. After some tests it seems to me it happens if there has to be done a lot of POW of different inputs. I passed 5 inputs from getInputs() to sendTransfer(). In this case iotaproxy always stops after 11 ccurl POWs without going further to broadcastTransaction etc.. and the client app throws following error between 5-7 ccurl calls: 


```
Error: Invalid Response: Error: socket hang up
    at createHangUpError (_http_client.js:253:15)
    at Socket.socketOnEnd (_http_client.js:345:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by TimSamshuijzen** [comment] 2017-09-09 21:54
@cyclux
So this happens when the PoW takes so long that the socket gets closed by some timeout?
@capaj "this is weird, because by default node.js socket does not have any timeout."
The server seems to have a timeout:

  https://stackoverflow.com/questions/23874954/is-there-a-default-timeout-in-nodejs-for-http-request

  https://stackoverflow.com/questions/23925284/how-to-modify-the-nodejs-request-default-timeout-time

In _http_server.js I found this:

  ```
Server.prototype.setTimeout = function(msecs, callback) {
    this.timeout = msecs;
    if (callback)
      this.on('timeout', callback);
    return this;
  };
```
Could this code play a role in this issue?

timeout defaults to 2 minutes, also stated here:
  https://nodejs.org/api/http.html

So does the PoW sometimes take longer than 2 minutes?

If so, I propose that this gets added to iotaproxy.js:

 `   this.server.setTimeout(15 * 60 * 1000); // 15 minutes timeout, allow enough time for PoW.`

I will do some testing.

**Comment by TimSamshuijzen** [comment] 2017-09-09 22:54
Tested by simulating long PoW, resulting in socket hangup, and could prevent it with the suggested fix, so I've committed the code.
@capaj and @cyclux : can you check whether the latest commit fixes the issue?
Thanks!

**Comment by cyclux** [comment] 2017-09-09 23:10
@TimSamshuijzen Cool! I wanted to test your suggestion earlier, but too much confirmation issues today :( Keep you posted!

**Comment by cyclux** [comment] 2017-09-10 01:29
@TimSamshuijzen I can confirm that the extension of timeout solves this issue!
I also experienced the `Invalid transaction hash` but will comment on that on the other thread.

**Comment by TimSamshuijzen** [comment] 2017-09-10 08:27
Great, thanks @cyclux. I will close this issue.
Look forward to your feedback on the other "Invalid transaction hash" thread.

**Closed as completed** 2017-09-10 08:27 UTC
